name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: build/  # Update if your build output is different

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages  # This is required for Pages deployment

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
